runtime: python38

handlers:
- url: /assets
  static_dir: assets

- url: .*
  script: main.app

# libraries:
# - name: webapp2
#   version: latest
# - name: jinja2
#   version: latest
# - name: markupsafe
#   version: latest
